title: "TEST Page"
#remote_theme: pmarsceill/just-the-docs
remote_theme: rivera10/Test-documentation
search_enabled: true

# Footer content
# appears at the bottom of every page's main content
footer_content: "Copyright"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
